# Generated by Django 4.2.16 on 2024-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0004_propertylisting_address"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="propertylisting",
            constraint=models.UniqueConstraint(
                fields=("list_id", "email"), name="unique_list_id_email"
            ),
        ),
    ]
