# Generated by Django 4.2.16 on 2024-11-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0005_propertylisting_unique_list_id_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="propertylisting",
            name="unique_list_id_email",
        ),
    ]
