# Generated by Django 4.2.16 on 2024-11-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbDemands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_type_code",
                    models.IntegerField(choices=[(1, "월세"), (2, "전세")]),
                ),
                ("house_type_name", models.CharField(editable=False, max_length=100)),
                (
                    "house_location_code",
                    models.IntegerField(
                        choices=[
                            (1, "강남구"),
                            (2, "강동구"),
                            (3, "강북구"),
                            (4, "강서구"),
                            (5, "관악구"),
                            (6, "광진구"),
                            (7, "구로구"),
                            (8, "금천구"),
                            (9, "노원구"),
                            (10, "도봉구"),
                            (11, "동대문구"),
                            (12, "동작구"),
                            (13, "마포구"),
                            (14, "서대문구"),
                            (15, "서초구"),
                            (16, "성동구"),
                            (17, "성북구"),
                            (18, "송파구"),
                            (19, "양천구"),
                            (20, "영등포구"),
                            (21, "용산구"),
                            (22, "은평구"),
                            (23, "종로구"),
                            (24, "중구"),
                            (25, "중랑구"),
                        ]
                    ),
                ),
                (
                    "house_location_name",
                    models.CharField(editable=False, max_length=100),
                ),
                ("house_min_price", models.IntegerField()),
                ("house_max_price", models.IntegerField()),
                (
                    "email",
                    models.ForeignKey(
                        db_column="email",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tbusers",
                    ),
                ),
            ],
        ),
    ]
