# Generated by Django 4.2.16 on 2024-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0002_alter_tbdemands_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbdemands",
            name="house_transaction_code",
            field=models.IntegerField(
                choices=[
                    (1, "아파트"),
                    (2, "빌라"),
                    (3, "단독주택"),
                    (4, "다가구주택"),
                    (5, "오피스텔"),
                ],
                default=1,
            ),
        ),
    ]
