# Generated by Django 4.2.16 on 2024-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0003_alter_tbdemands_house_transaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbdemands",
            name="post_title",
            field=models.CharField(default="제목을 입력해주세요", max_length=100),
        ),
    ]
