# Generated by Django 4.2.16 on 2024-11-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0005_tbdemands_image1_tbdemands_image2_tbdemands_image3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbdemands",
            name="house_location_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tbdemands",
            name="house_transaction_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tbdemands",
            name="house_type_name",
            field=models.CharField(max_length=100),
        ),
    ]
